######################################Llava-lora-Quilt-B-32-vicuna##########################################
##############################################################################################################
#####stage1_pretrain#########
OMP_NUM_THREADS=8 deepspeed  --include localhost:4 --master_port=25902 llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version plain \
    --data_path ./playground/dpo_data/quilt_data/quilt_pretrain.json \
    --image_folder ./playground/dpo_data/quilt_data/quilt \
    --vision_tower wisdomik/QuiltNet-B-32 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints1/Llava-lora-Quilt-B-32-vicuna-stage1 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 128 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb \
    --run_name Llava-lora-Quilt-B-32-vicuna-stage1
######stage2_finetune##########
OMP_NUM_THREADS=8 deepspeed  --include localhost:4 --master_port=25902 llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5 \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --version v1 \
    --data_path ./playground/dpo_data/quilt_data/quilt_instruct_107k.json \
    --image_folder ./playground/dpo_data/quilt_data/quilt_instruct \
    --vision_tower wisdomik/QuiltNet-B-32 \
    --pretrain_mm_mlp_adapter ./checkpoints1/Llava-lora-Quilt-B-32-vicuna-stage1_epoch3/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length False \
    --bf16 True \
    --output_dir ./checkpoints1/Llava-lora-Quilt-B-32-vicuna-stage2_epoch3_1 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 128 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-4 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb \
    --run_name Llava-lora-Quilt-B-32-vicuna-stage2_epoch3_1
######merge_lora_weights##########
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=8 python scripts/merge_lora_weights.py \
    --model-path "./checkpoints1/Llava-lora-Quilt-B-32-vicuna-stage2" \
    --model-base lmsys/vicuna-7b-v1.5 \
    --save-model-path "./checkpoints1/Llava-lora-Quilt-B-32-vicuna-merged"
######stage3_dpo################
OMP_NUM_THREADS=8 deepspeed  --include localhost:0 --master_port=25900  seva/train_dpo_ours.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 0 \
    --deepspeed seva/scripts/zero3.json \
    --model_name_or_path ./checkpoints1/Llava-lora-Quilt-B-32-vicuna-merged \
    --version v1 \
    --textvqa_data_path playground/dpo_data/step3/dpo_data.json \
    --textvqa_image_path playground/dpo_data/quilt_data/quilt_instruct/ \
    --vision_tower wisdomik/QuiltNet-B-32 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length False \
    --bf16 True \
    --output_dir ./checkpoints1/Llava-lora-Quilt-B-32-vicuna-stage3 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 128 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 50000 \
    --save_total_limit 1 \
    --learning_rate 2e-6 \
    --weight_decay 0. \
    --warmup_steps 0 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb \
    --run_name Llava-lora-Quilt-B-32-vicuna-stage3__20k_gt_quiltllava \
    --beta 0.1
######merge_lora_weights##########
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=8 python scripts/merge_lora_weights.py \
    --model-path "./checkpoints1/Llava-lora-Quilt-B-32-vicuna-stage3" \
    --model-base ./checkpoints1/Llava-lora-Quilt-B-32-vicuna-merged \
    --save-model-path "./checkpoints1/Llava-lora-Quilt-B-32-vicuna"